### ISSUE TITLE
ERROR: Distribution "Debian GNU/Linux 9 (stretch)" is not supported!

### ISSUE THREAD

**Issue by Jason-cqtan** [johnrosen1/trojan-gfw-script#1]
自动脚本说是不支持Debian 9，系统32位的，vps是512m内存搬瓦工

**Comment by johnrosen1** [comment]
我的自动探测目前不支持32位系统，建议使用64位的，你也可以用旧版本，那个没有自动探测

**Comment by Jason-cqtan** [comment]
按你网站说明，手动配置支持32位吗

**Comment by johnrosen1** [comment]
https://github.com/johnrosen1/trojan-gfw-script/blob/master/trojanv0.1.sh

**Comment by Jason-cqtan** [comment]
![image](https://user-images.githubusercontent.com/17697213/70843693-c72d6480-1e71-11ea-9817-5b4555f66e04.png)

**Comment by johnrosen1** [comment]
呃，实在不行你就手动配置吧

**Comment by Jason-cqtan** [comment]
好的，谢谢

**Comment by johnrosen1** [comment]
不推荐使用32位系统

**Comment by Jason-cqtan** [comment]
主要是配置低，之前搭了些服务，换64位又得重新装😅

**Comment by johnrosen1** [comment]
好吧
