### ISSUE TITLE
教程请求

### ISSUE THREAD

**Issue by mieshui** [johnrosen1/trojan-gfw-script#11]
你好，我是通过你的博客来到这里的。博主在教程中写过“Trojan可以和现有网站共存，Nginx之类的Web server关掉Tls，Trojan的服务端的remote_addr以及remote_port指向后端的非Tls端口就行。”
请问应该如何操作呢，新人没搞懂，谢谢。

**Comment by johnrosen1** [comment]
nginx不开tls就行了

**Comment by mieshui** [comment]
也就是说，网站会变成http而不可能有HTTPS对吗?

**Comment by johnrosen1** [comment]
你没有理解trojan的原理

**Comment by mieshui** [comment]
还是没搞懂，请问能具体说说吗？

**Comment by johnrosen1** [comment]
总之你试试就知道了，多做少问
