### ISSUE TITLE
在安装界面选择了安装BBR和BBR PLUS，结果没有安装成功

### ISSUE THREAD

**Issue by zhangsean** [johnrosen1/trojan-gfw-script#14]
在安装界面选择了安装BBR和BBR PLUS，结果没有安装成功
安装结果展示前一步有显示一个界面核心已安装，加速器未安装，当时输入11退出了。
安装界面选择安装BBR和BBR PLUS不能传参数给这个加速器吗？
然后怎么重新进入这个加速器安装界面？

**Comment by johnrosen1** [comment]
@zhangsean 你应该问他们
https://github.com/chiakge/Linux-NetSpeed
