### ISSUE TITLE
请教，新版本的更换/

### ISSUE THREAD

**Issue by StevenJokes** [johnrosen1/trojan-gfw-script#20]
大佬，好奇为什么删去v2ray，rss的脚本，毕竟Trojan的win10用法还是很繁琐。可能是我菜，二维码无法导入/服务器也只能一个一个设置。。。以及问下 trojan二维码 怎么用方便？只能一个一个设置文件json吗

**Comment by johnrosen1** [comment]
@StevenJokes 想要方便请自己开发客户端（

**Comment by StevenJokes** [comment]
？好奇为什么删去v2ray，rss的脚本

**Comment by johnrosen1** [comment]
@StevenJokes 我不需要了

**Comment by StevenJokes** [comment]
是现有的客户端基本上都不方便吗？大佬

**Comment by johnrosen1** [comment]
@StevenJokes 不是（

**Comment by StevenJokes** [comment]
Trojan，我用的是V2rayN套Socks。还有方法就是SwitchyOmega插件。。还有别的客户端推荐吗？

**Comment by johnrosen1** [comment]
@StevenJokes 你自己开发一个就行（

**Comment by cash714** [comment]
> Trojan，我用的是V2rayN套Socks。还有方法就是SwitchyOmega插件。。还有别的客户端推荐吗？

Clash套。和v2rayN一样，还有规则用
