### ISSUE TITLE
Vmess V2ray

### ISSUE THREAD

**Issue by aeroweb340** [johnrosen1/trojan-gfw-script#21]
I'm a huge fan of this script but why did you remove the v2ray install?

**Comment by johnrosen1** [comment]
@aeroweb340 https://drive.google.com/open?id=16Hsxk_L4aXo14MDne4ufUve0Q1et332q

**Comment by aeroweb340** [comment]
Thanks ! I have installed v2ray along side Trojan. I have deployed it on a ScaleWay server(France). Trojan is fast but Vmess is slow. Is there something I should tweak?
