### ISSUE TITLE
nginx 启动报错

### ISSUE THREAD

**Issue by jockeyvv** [johnrosen1/trojan-gfw-script#27]
[root@0a0 ~]# sudo systemctl status trojan
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: active (running) since 一 2020-03-02 10:10:50 HKT; 1min 12s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 1024 (trojan)
   CGroup: /system.slice/trojan.service
           └─1024 /usr/local/bin/trojan /usr/local/etc/trojan/config.json

3月 02 10:11:41 0a0.xyz trojan[1024]: [2020-03-02 10:11:41] [INFO] ::ffff:...ds
3月 02 10:11:50 0a0.xyz trojan[1024]: [2020-03-02 10:11:50] [WARN] ::ffff:...80
3月 02 10:11:50 0a0.xyz trojan[1024]: [2020-03-02 10:11:50] [ERROR] ::ffff...ed
3月 02 10:11:50 0a0.xyz trojan[1024]: [2020-03-02 10:11:50] [INFO] ::ffff:...ds
3月 02 10:11:51 0a0.xyz trojan[1024]: [2020-03-02 10:11:51] [WARN] ::ffff:...80
3月 02 10:11:51 0a0.xyz trojan[1024]: [2020-03-02 10:11:51] [ERROR] ::ffff...ed
3月 02 10:11:51 0a0.xyz trojan[1024]: [2020-03-02 10:11:51] [INFO] ::ffff:...ds
3月 02 10:11:54 0a0.xyz trojan[1024]: [2020-03-02 10:11:54] [WARN] ::ffff:...80
3月 02 10:11:54 0a0.xyz trojan[1024]: [2020-03-02 10:11:54] [ERROR] ::ffff...ed
3月 02 10:11:54 0a0.xyz trojan[1024]: [2020-03-02 10:11:54] [INFO] ::ffff:...ds
Hint: Some lines were ellipsized, use -l to show in full.
[root@0a0 ~]# sudo systemctl status nginx
● nginx.service - The NGINX HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 一 2020-03-02 10:12:17 HKT; 1s ago
  Process: 1671 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)

3月 02 10:12:17  systemd[1]: Failed to start The NGINX HTTP and rev...r.
3月 02 10:12:17  systemd[1]: Unit nginx.service entered failed state.
3月 02 10:12:17 systemd[1]: nginx.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@0a0 ~]# sudo nginx
nginx: [emerg] unknown directive "stub_status" in /etc/nginx/conf.d/trojan.conf:122

**Comment by johnrosen1** [comment]
please paste your os info

**Comment by johnrosen1** [comment]
@jockeyvv cat /etc/*release please give me your os info

**Comment by jockeyvv** [comment]
> @jockeyvv cat /etc/*release please give me your os info

[root@0a0 /]# cat /etc/*release
CentOS Linux release 7.7.1908 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.7.1908 (Core)
CentOS Linux release 7.7.1908 (Core)

**Comment by johnrosen1** [comment]
@jockeyvv all right i will fix it

**Comment by johnrosen1** [comment]
@jockeyvv fix complete !
