### ISSUE TITLE
ip被墙的问题

### ISSUE THREAD

**Issue by harry3633** [johnrosen1/trojan-gfw-script#28]
我在一台ipv6 only服务器上安装此脚本，开始即提示你的ip被墙了，我不知道检测的是什么ip，这个提示直接中断了安装，感觉有些不合适，即便是真的被墙了，还可以用cdn来救一下嘛，是否只提示不中断安装呢？谢谢

**Comment by johnrosen1** [comment]
@harry3633 i will try to fix it

**Comment by johnrosen1** [comment]
@harry3633 fix complete!
