### ISSUE TITLE
BBR Values

### ISSUE THREAD

**Issue by aliabbasian1198** [johnrosen1/trojan-gfw-script#32]
Hi Dear
Question1:
The following value is different
net.ipv4.tcp_mtu_probing = ?
https://github.com/johnrosen1/trojan-gfw-script/blob/master/vps.sh
https://github.com/johnrosen1/trojan-gfw-script/blob/master/conf/BBR/99-sysctl.conf

Question2:
net.ipv4.tcp_timestamps = ?
0 or 1
Thanks

**Comment by johnrosen1** [comment]
@aliabbasian1198 oh i forgot to update

**Comment by johnrosen1** [comment]
@aliabbasian1198 fixed and tcp timestamps maybe is better to be 1 according to my observation
