### ISSUE TITLE
最新脚本有BUG，trojan停止运行

### ISSUE THREAD

**Issue by lyin888** [johnrosen1/trojan-gfw-script#33]
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-03-23 16:36:38 HKT; 2s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 3673 ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 3673 (code=exited, status=1/FAILURE)

 3月 23 16:36:38 hk systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
 3月 23 16:36:38 hk systemd[1]: trojan.service: Unit entered failed state.
 3月 23 16:36:38 hk systemd[1]: trojan.service: Failed with result 'exit-code'.

**Comment by johnrosen1** [comment]
@lyin888 all right i will try to solve it

**Comment by johnrosen1** [comment]
@lyin888 journalctl -a -u trojan.service       please give me log

**Comment by lyin888** [comment]
root@hk:~# journalctl -a -u trojan.service please give me log
Failed to add match 'please': 不適用的引數

**Comment by lyin888** [comment]
-- Logs begin at Mon 2020-03-23 16:51:51 HKT, end at Mon 2020-03-23 16:52:39 HKT. --
 3月 23 16:51:53 hk systemd[1]: Started trojan.
 3月 23 16:51:53 hk trojan[481]: Welcome to trojan 1.15.0
 3月 23 16:51:53 hk trojan[481]: [2020-03-23 16:51:53] [FATAL] fatal: use_certificate_chain_file: No such file or directory
 3月 23 16:51:53 hk trojan[481]: [2020-03-23 16:51:53] [FATAL] exiting. . .
 3月 23 16:51:53 hk systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
 3月 23 16:51:53 hk systemd[1]: trojan.service: Unit entered failed state.
 3月 23 16:51:53 hk systemd[1]: trojan.service: Failed with result 'exit-code'.
 3月 23 16:51:57 hk systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
 3月 23 16:51:57 hk systemd[1]: Stopped trojan.
 3月 23 16:51:57 hk systemd[1]: Started trojan.
 3月 23 16:51:57 hk trojan[879]: Welcome to trojan 1.15.0
 3月 23 16:51:57 hk trojan[879]: [2020-03-23 16:51:57] [FATAL] fatal: use_certificate_chain_file: No such file or directory
 3月 23 16:51:57 hk trojan[879]: [2020-03-23 16:51:57] [FATAL] exiting. . .
 3月 23 16:51:57 hk systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
 3月 23 16:51:57 hk systemd[1]: trojan.service: Unit entered failed state.
 3月 23 16:51:57 hk systemd[1]: trojan.service: Failed with result 'exit-code'.
 3月 23 16:52:00 hk systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
 3月 23 16:52:00 hk systemd[1]: Stopped trojan.
 3月 23 16:52:00 hk systemd[1]: Started trojan.
 3月 23 16:52:00 hk trojan[947]: Welcome to trojan 1.15.0
 3月 23 16:52:00 hk trojan[947]: [2020-03-23 16:52:00] [FATAL] fatal: use_certificate_chain_file: No such file or directory
 3月 23 16:52:00 hk trojan[947]: [2020-03-23 16:52:00] [FATAL] exiting. . .
 3月 23 16:52:00 hk systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
 3月 23 16:52:00 hk systemd[1]: trojan.service: Unit entered failed state.
 3月 23 16:52:00 hk systemd[1]: trojan.service: Failed with result 'exit-code'.
 3月 23 16:52:03 hk systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
 3月 23 16:52:03 hk systemd[1]: Stopped trojan.
 3月 23 16:52:03 hk systemd[1]: Started trojan.
 3月 23 16:52:03 hk trojan[964]: Welcome to trojan 1.15.0
 3月 23 16:52:03 hk trojan[964]: [2020-03-23 16:52:03] [FATAL] fatal: use_certificate_chain_file: No such file or directory
 3月 23 16:52:03 hk trojan[964]: [2020-03-23 16:52:03] [FATAL] exiting. . .
 3月 23 16:52:03 hk systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
 3月 23 16:52:03 hk systemd[1]: trojan.service: Unit entered failed state.
 3月 23 16:52:03 hk systemd[1]: trojan.service: Failed with result 'exit-code'.
 3月 23 16:52:07 hk systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
 3月 23 16:52:07 hk systemd[1]: Stopped trojan.
 3月 23 16:52:07 hk systemd[1]: Started trojan.

**Comment by johnrosen1** [comment]
@lyin888 your certificate issue failed,please check it by yourself

**Comment by johnrosen1** [comment]
@lyin888 it is your problem after all ,plese solve it by yourself
