### ISSUE TITLE
sslv3 alert bad certificate

### ISSUE THREAD

**Issue by guoPengSong** [johnrosen1/trojan-gfw-script#37]
<img width="964" alt="WeChat724b74ad3166a29bc785bedb20efc371" src="https://user-images.githubusercontent.com/17527334/78143057-4c0fae80-7460-11ea-8252-886f7cd05170.png">
这是为什么？证书问题吗？之前是能用的

**Comment by johnrosen1** [comment]
@guoPengSong not a problem,please update your software
