### ISSUE TITLE
unsupported option "noProtocol"

### ISSUE THREAD

**Issue by puyongcl** [johnrosen1/trojan-gfw-script#38]
-- A stop job for unit ssh.service has finished.
-- 
-- The job identifier is 1488 and the job result is done.
Apr 02 00:32:23 ecs-efce systemd[1]: ssh.service: Start request repeated too quickly.
Apr 02 00:32:23 ecs-efce systemd[1]: ssh.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit ssh.service has entered the 'failed' state with result 'exit-code'.
Apr 02 00:32:23 ecs-efce systemd[1]: Failed to start OpenBSD Secure Shell server.
-- Subject: A start job for unit ssh.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit ssh.service has finished with a failure.
-- 
-- The job identifier is 1488 and the job result is failed.
root@ecs-efce:/var/run# /usr/sbin/sshd -T
/etc/ssh/sshd_config line 124: unsupported option "noProtocol".

**Comment by johnrosen1** [comment]
@puyongcl please provide more log and info

**Comment by puyongcl** [comment]
error in sshd_config , "useDNS no Protocol" 2, the two config in the same line, change it to diff line, ssh wrok. cause the error, when begin bash the vps.sh, maybe after choose language

**Comment by puyongcl** [comment]
> error in sshd_config , "useDNS no Protocol" 2, the two config in the same line, change it to diff line, ssh wrok. cause the error, when begin bash the vps.sh, maybe after choose language



> @puyongcl please provide more log and info

**Comment by johnrosen1** [comment]
@puyongcl then it is your own fault not related to this project
