### ISSUE TITLE
现有V2RAY有断流现象

### ISSUE THREAD

**Issue by browningfai** [johnrosen1/trojan-gfw-script#4]
脚本默认配置的v2ray有出现一个时间段彻底无法连接，或者在看视频的时候有断流的现象。网络环境4G 、WIFI都是，运营商均为联通，主机商vultr线路日本。
希望大佬能加入V2RAY详细自定义配置的功能以及TLS1.3ONLY的功能。
alterid希望可以自定义设置，原先默认设置比较大。
WS host希望可以加入原域名。
v2ray的域名希望可以设置和木马的不同。

**Comment by browningfai** [comment]
还希望大佬能开一个TG讨论群让大家一起讨论脚本。补充，我使用的是1217晚间出的最新脚本。VPS线路没问题，我的其他V2RAY线路正常连接，用的WULABING的脚本。

**Comment by johnrosen1** [comment]
行，等我建

**Comment by johnrosen1** [comment]
t.me/trojanscript
