### ISSUE TITLE
20191218版本在centos7.7出错

### ISSUE THREAD

**Issue by flyhigao** [johnrosen1/trojan-gfw-script#5]
我在bandwagon上新建了一台centos7.7, 脚本运行出错, 是在yum install的地方,有几个软件包都not avaiable. 导致后面nginx各种错误. 
于是我重建了系统,这次用debian9,就一切正常了. 
没有保留下centos7.7出错的场景,但很容易重现,通报下.

**Comment by johnrosen1** [comment]
package not found的列出来，不然修不了

**Comment by johnrosen1** [comment]
已修复
