### ISSUE TITLE
centos7 下遇到的问题

### ISSUE THREAD

**Issue by ylx2016** [johnrosen1/trojan-gfw-script#7]
nslookup 缺少依赖组件
yum install bind-utils -y

nginx 报错
nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/nginx.conf:39
需要注释nginx默认带的80或者改其他端口
剩下的我自己手动完成

**Comment by johnrosen1** [comment]
依赖已修复，至于ctos适配问题你自己修改代码提交pr吧，我不好

> nslookup 缺少依赖组件
> yum install bind-utils -y
> 
> nginx 报错
> nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/nginx.conf:39
> 需要注释nginx默认带的80或者改其他端口
> 剩下的我自己手动完成

依赖已修复，至于ctos下的nginx适配你自己修改代码提交pr就行

**Comment by johnrosen1** [comment]
已修复
