### ISSUE TITLE
应该采用bbrplus，速度更快更稳定

### ISSUE THREAD

**Issue by geerda123** [johnrosen1/trojan-gfw-script#8]
bbr的效果没有bbrplus，应该增加一键换脚本命令，而且安装时（debian9）会缺少Failed to create bus connection: No such file or directory

需要apt-get install dbus

**Comment by johnrosen1** [comment]
bbrplus我不会，给个链接我看看，dbus倒是不难，加上即可

**Comment by johnrosen1** [comment]
dbus已添加

**Comment by geerda123** [comment]
@johnrosen1 
https://github.com/chiakge/Linux-NetSpeed/

**Comment by johnrosen1** [comment]
好的，我看看去

**Comment by johnrosen1** [comment]
要不你来我们群里讨论，主要是我不知道bbrplus是否有必要

**Comment by geerda123** [comment]
好的，bbrplus是修正了bbr的错误，你看它的来源。Trojan网上教程大部分搭配bbrplus

**Comment by johnrosen1** [comment]
要不我就再开一个BBRPULS版本好了，现有版本我不想动

**Comment by geerda123** [comment]
我只是说一下，自己装也可以，没必要集成了，我只是说一下

johnrosen1 <notifications@github.com> 于 2020年1月6日周一 12:53写道：

**Comment by johnrosen1** [comment]
行吧，已添加
